modLoader="javafml" 

loaderVersion="[31,)" 

[[mods]] 

modId="humbercraft" 

version="1.0.0"

displayName="HumberCraft" 

credits="HumberCode Team" 

description='''
	To Be Determined.
'''

[[dependencies.humbercraft]]
    modId="forge" 
    mandatory=true 
    versionRange="[31,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.humbercraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
